apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      app.openshift.io/vcs-ref: master
      app.openshift.io/vcs-uri: https://github.com/IndraniDey1/spring-boot-s2i-app.git
    creationTimestamp: "2020-05-05T05:38:27Z"
    labels:
      app: spring-boot-s2i-app-git
      app.kubernetes.io/component: spring-boot-s2i-app-git
      app.kubernetes.io/instance: spring-boot-s2i-app-git
      app.kubernetes.io/name: java
      app.kubernetes.io/part-of: spring-boot-s-2-i-app-git-app
      app.openshift.io/runtime: java
      app.openshift.io/runtime-version: "8"
    name: spring-boot-s2i-app-git
    namespace: s2i-app-with-build
    resourceVersion: "2308008"
    selfLink: /apis/build.openshift.io/v1/namespaces/s2i-app-with-build/buildconfigs/spring-boot-s2i-app-git
    uid: 0d364ac8-6181-4446-ac51-5fd6a3ef94fa
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: spring-boot-s2i-app-git:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /
      git:
        uri: https://github.com/IndraniDey1/spring-boot-s2i-app.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: java:8
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - generic:
        secretReference:
          name: spring-boot-s2i-app-git-generic-webhook-secret
      type: Generic
    - github:
        secretReference:
          name: spring-boot-s2i-app-git-github-webhook-secret
      type: GitHub
    - imageChange:
        lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/java@sha256:4d81fc29c2069dc588ff8a77f144813772de3cb2a24c2a5b9ec78f7201190a62
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
