apiVersion: v1
kind: Secret
metadata:
  name: mysql 
  type: Opaque
data:
  database-user: dXNlcjE=
  database-password: cGFzc3dvcmQ=
  database-root-password: cGFzc3dvcmQ=
  database-name: Ym9va3N0b3Jl
